version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: next_mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nextdb
      MYSQL_USER: nextuser
      MYSQL_PASSWORD: password123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: